# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: b6407ea
_src_path: gh:scipp/copier_template
description: SANS data reduction for the European Spallation Source
github_linux_image: ubuntu-20.04
max_python: '3.11'
min_python: '3.8'
orgname: scipp
projectname: esssans
year: 2023
