# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 12bf466
_src_path: gh:scipp/copier_template
description: SANS data reduction for the European Spallation Source
max_python: '3.12'
min_python: '3.8'
orgname: scipp
projectname: esssans
year: 2023
