# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 80abba4
_src_path: gh:scipp/copier_template
description: SANS data reduction for the European Spallation Source
max_python: '3.12'
min_python: '3.8'
namespace_package: ''
nightly_deps: plopp,sciline,scippneutron,scippnexus,scipp
orgname: scipp
projectname: esssans
related_projects: Scipp,ScippNexus,ScippNeutron,Sciline,Plopp
year: 2023
