package:
  name: esssans

  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..

requirements:
  build:
    - setuptools
    - setuptools_scm
  run:
    - dask
    - python>=3.9
    - python-graphviz
    - plopp
    - pythreejs
    - sciline>=23.9.1
    - scipp>=23.8.0
    - scippneutron>=23.9.0

test:
  imports:
    - esssans
  requires:
    - pytest
  source_files:
    - pyproject.toml
    - tests/
  commands:
    # We ignore warnings during release package builds
    - python -m pytest -Wignore tests

build:
  noarch: python
  script:
    - python -m pip install .

about:
  home: https://github.com/scipp/esssans
  license: BSD-3-Clause
  summary: SANS data reduction for the European Spallation Source
  description: SANS data reduction for the European Spallation Source
  dev_url: https://github.com/scipp/esssans
  doc_url: https://scipp.github.io/esssans
