import re
from argparse import ArgumentParser

parser = ArgumentParser()
parser.add_argument(
    '--nightly',
    nargs='*',
    default=[],
    help='List of dependencies to install from main branch for nightly tests.',
)
args = parser.parse_args()

dependencies = []
with open('base.in', 'w') as f:
    f.write('# Generated by \'tox -e deps\', DO NOT EDIT MANUALLY!\n')
    with open('../pyproject.toml', 'r') as toml_file:
        toml_contents = toml_file.read()
        match = re.search(r'dependencies = \[(.*?)\]', toml_contents, re.DOTALL)
        if match:
            for dependency in match.group(1).split(',\n'):
                dependency = dependency.strip().strip('"')
                if dependency:
                    dependencies.append(dependency)
                    f.write(dependency + '\n')

with open('nightly.in', 'w') as f:
    f.write('# Generated by \'tox -e deps\', DO NOT EDIT MANUALLY!\n')
    for dependency in dependencies:
        for arg in args.nightly:
            if dependency.startswith(arg):
                f.write(f'{arg} @ git+https://github.com/scipp/{arg}@main' + '\n')
                break
        else:
            f.write(dependency + '\n')
